### ISSUE TITLE
wow such cpp homework!

### ISSUE THREAD

**Issue by LugiaIO** [c3ll256/Cpp_class#1]
1145141919810 👍🏼

**Comment by c3ll256** [comment]
![image](https://user-images.githubusercontent.com/27946357/102720914-28fc9600-4332-11eb-904b-fd77b4f09eb9.png)

**Comment by AIVesper** [comment]
![Uploading 0E663E13-D2C5-4F7B-AFE4-CA9E8296CBB5.jpeg…]()

**Comment by LugiaIO** [comment]
![Uploading 09F3EC8F-9940-4099-A86E-158556657C2C.png…]()
